### ISSUE TITLE
Having problem that client not sending messages

### ISSUE THREAD

**Issue by Alex0007** [cgeorg/cycle-socket.io#10]
Can you look at this and tell me, what is the problem here, why i don't get messages back from client?

https://github.com/Alex0007/cycle-socket.io-problem

**Comment by cgeorg** [comment]
Hi Alex,

I took a look and I'm not sure what the problem is - it looks the the function in the driver that maps the events to the publish command isn't getting hit. I haven't used xstream, I just merged the pulll request - can you look at the code in that area to see what the problem might be?

**Comment by Alex0007** [comment]
Can you publish xs working version? I can't use just github link as dependency because of npm prepublish task

**Comment by cgeorg** [comment]
Published the fix as v3.0.1 to npm
