### ISSUE TITLE
2.0.0 -> 2.0.1 webpack support broken

### ISSUE THREAD

**Issue by Alex0007** [cgeorg/cycle-socket.io#9]
Just updated this package in deps and webpack started to return error:

```
ERROR in ./app.js
Module not found: Error: Cannot resolve module 'cycle-socket.io' in /home/alex/Development/projects/lps-da-webui/client
 @ ./app.js 17:19-45
```

**Comment by cgeorg** [comment]
I just published a new version - I had missed a change in package.json. I'm not in a place where I can test this - can you verify that 2.0.2 works?

**Comment by Alex0007** [comment]
Working now! Thanks
